pipeline {
    agent any

    stages {
        stage('Compile') {
            steps {
                dir('api-testing') { 
                    bat 'mvn clean compile'
                    }                    
               
            }
        }
        stage('Testing') {
            steps {
                   dir('api-testing'){
                      bat 'mvn clean test'
                   }              
            }
        }
        stage('Publish reports') {
            steps{
		dir('api-testing'){
			publishHTML([
			reportDir: './target/surefire-reports',
			reportFiles: 'index.html',
			reportName: 'HTML Report'
			])}
		}
           }
      }
}
