pipeline {
    agent any

    stages {
        stage('Compile') {
            steps {
               bat 'cd ./api-testing'
               bat 'mvn clean compile'
               
            }
        }
        stage('Testing') {
            steps {
                    bat 'cd ./api-testing'
                    bat 'mvn clean test'
                
            }
        }
      }
}
